logo: ./pic/logo.jpg
description: >
  NEST+m, New Explorations into Science, Technology + Math, is a K-12 public school located in
  the Lower East Side of New York City. This project seeks a low-cost solution for reducing the reverberation time 
  while also engaging the schools’ students in a creative and interactive project. It is a chance for the
  Cooper Union Acoustic and Vibration Laboratpry to give back and engange in community outreach. 
  <br><br>


theme: jekyll-theme-minimal
