logo: ./logo.png
description: >
  NEST+m is a local k-12 public school located in the lower east side of Manhattan, New York. They approch to us, the Cooper Union Acouistic and Vibration Laboratory for help
  because of their auditorium's bad acoustical environment. The school's auditorium is fan-shaped witha volumn of about 529 seats. The school is concenred due to auditorium's 
  high reverberation time(echoness) and low intelligibility. 
  <br><br>
  My teammate and I offered the school a proposed solution based on our meaurement during the site visit. The proposed solution was backed up using CATT Acoutsic modeling.
  After NEST+m acceptted our proposal, we did another measurement to see if the expected improvment is accomplished. 
  <br><br>

  <a href='https://www.linkedin.com/in/mingyang-lee-a5019199/'>View The Github Profile</a>

theme: jekyll-theme-minimal
