logo: ./pic/logo.jpg
description: >
  NEST+m, New Explorations into Science, Technology + Math, is a K-12 public school located in
  the Lower East Side of New York City. The NEST+m auditorium is fan-shaped with a volume of 100,000
  ft3 (about 2900 m3) and 529 seats. This auditorium’s acoustics is relatively poor due to its high
  reverberation time making the clarity of speech very low.
  <br><br>
  This project seeks a low-cost solution for reducing the reverberation time while also engaging the
  schools’ students in a creative and interactive project. The NEST+m students can learn about the basic
  knowledge of auditorium acoustics, and engage in a hands-on, creative project by decorating their
  auditorium with the proposed acoustic panels. The panels can be detachable and removed when more
  reverberation is desired, for example, during concerts.accomplished. It is also a chance for the
  Cooper Union Acoustic and Vibration Laboratpry to give back and engange in community outreach. 
  <br><br>

  <a href='https://www.linkedin.com/in/mingyang-lee-a5019199/'>View The Github Profile</a>

theme: jekyll-theme-minimal
