logo: ./pic/logo.jpg
description: >
  This project seeks a low-cost solution for reducing the reverberation time of a local public school's auditorium, 
  It is a chance for the Cooper Union Acoustic and Vibration Laboratpry to give back and engange in community outreach. 
  <br><br>

  <a href='https://raymondminglee.github.io/'>Back to Protfolio</a>

theme: jekyll-theme-minimal
